name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install en_US.UTF-8 locale
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale

      - name: Lint
        run: bash scripts/ci.sh --lint

      - name: Test
        run: bash scripts/ci.sh --test
        env:
          LC_ALL: en_US.UTF-8
